### PR TITLE
Move example code to README

### PR DESCRIPTION
**Pull request by abeltay**
Referencing: https://github.com/moexmen/gokit/commit/f340814cf5fcfd8c01d4f5517a16d28cb8ed6111

The code `exampleServer.go` was added so that dep can correctly identify this repo as a Go repo. However, the file is not really used and the example code is better put into the README as a reference.

This is replaced with a file named `dummyCode.go` and using a non-exported variable in the code to clearly state its purpose as "not used" .

### CODE REVIEW

**Comment by sohymg** [comment]
> The code exampleServer.go was added so that dep can correctly identify this repo as a Go repo. 

What is the criteria to be identified as a Go repo?

**Comment by abeltay** [comment]
You literally need to have `.go` files in the root folder. Otherwise `dep` will not recognise it as a Go repo.

**Comment by sohymg** [comment]
I see, then how about call that file `main.go` since the package inside is main and add the comment inside to say what this file is for? Also is the `foo struct` needed?

**Comment by abeltay** [comment]
`main.go` gives the idea that it is the entrypoint to create the binary for this code, which is not the impression we want to give here.

`foo struct` is not needed, in fact it can be an empty file. To be more minimalistic, I can call the file `depCompatibility.go` and keep it empty. It should satisfy the intended purpose.

**Comment by abeltay** [comment]
I tested with an empty file and got the following error,
```
Could not introduce github.com/moexmen/gokit, as its subpackage github.com/moexmen/gokit does not contain usable Go code (scanner.ErrorList).. (Package is required by (root).)
```
The most minimalistic solution would be to add a file containing only
```
package main
```

**Comment by sohymg** [comment]
In that case, can you add the comment in `depCompatibility.go` to explain the rationale? I think the convention in Go is to use snake case instead of camel case for file names. And maybe `dep.go` is good enough a name with comments inside.

**Comment by abeltay** [comment]
Renamed.

**Review by sohymg — APPROVED** [review]

**Pull request merged**
